export const products = [
	{
		id: 1,
		name: "Diamond Whale Tail",
		sale: true,
		originalPrice: 35.0,
		discountedPrice: null,
		imagePath: "./assets/img/products/1.png",
		starsNum: 3,
		weight: "40g",
		material: "diamond, gold",
		available: true,
	},
	{
		id: 2,
		name: "Lovely Cat Face",
		sale: true,
		originalPrice: 20.0,
		discountedPrice: 18.55,
		imagePath: "./assets/img/products/2.png",
		starsNum: 4,
		weight: "30g",
		material: "gold, white spray paint",
		available: true,
	},
	{
		id: 3,
		name: "Fortune Tiger Lord",
		sale: true,
		originalPrice: 50.25,
		discountedPrice: 29.99,
		imagePath: "./assets/img/products/3.png",
		starsNum: 5,
		weight: "60g",
		material: "gold, black spray paint",
		available: false,
	},
	{
		name: "Gold Bear",
		sale: true,
		originalPrice: 60.25,
		discountedPrice: 39.99,
		imagePath: "./assets/img/products/4.png",
		starsNum: 5,
		weight: "60g",
		material: "gold, black spray paint",
		available: false,
	},
	{
		name: "Little cute pig",
		sale: true,
		originalPrice: 35.25,
		discountedPrice: 5.99,
		imagePath: "./assets/img/products/5.png",
		starsNum: 5,
		weight: "60g",
		material: "gold, black spray paint",
		available: false,
	},
	{
		name: "Little cute fox",
		sale: true,
		originalPrice: 25.25,
		discountedPrice: 10.99,
		imagePath: "./assets/img/products/6.png",
		starsNum: 5,
		weight: "60g",
		material: "gold, black spray paint",
		available: false,
	},
	{
		name: "Fortune old man",
		sale: false,
		originalPrice: 30,
		discountedPrice: 20.99,
		imagePath: "./assets/img/products/7.png",
		starsNum: 5,
		weight: "60g",
		material: "gold, black spray paint",
		available: false,
	},
	{
		name: "Little cute long dog",
		sale: true,
		originalPrice: 60.25,
		discountedPrice: 29.99,
		imagePath: "./assets/img/products/8.png",
		starsNum: 5,
		weight: "60g",
		material: "gold, black spray paint",
		available: false,
	},
	{
		name: "Fortune old fox",
		sale: false,
		originalPrice: 30,
		discountedPrice: 20.99,
		imagePath: "./assets/img/products/9.png",
		starsNum: 5,
		weight: "60g",
		material: "gold, black spray paint",
		available: false,
	},
	{
		name: "Little cute long fox",
		sale: true,
		originalPrice: 60.25,
		discountedPrice: 29.99,
		imagePath: "./assets/img/products/10.png",
		starsNum: 5,
		weight: "60g",
		material: "gold, black spray paint",
		available: false,
	},
];
